import './global.css';
import { AuthProvider } from '../contexts/AuthContext';
import { Toaster } from 'sonner';
export const metadata = {
  title: 'Đấu giá Thành Công',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          {children}
          <Toaster richColors />
        </AuthProvider>
      </body>
    </html>
  );
}
